name: pretty_json
description: A small wrapper for pretty printing JSON objects in a more human readable format. Typically this package would be used for network logging and debugging objects. This package is very small and could be implemented in a project, the package is just to keep code neat and avoid duplication. For some reason this description has to be 60+ words otherwise points get subtracted, enjoy.
version: 1.0.2

homepage: https://github.com/Ferdzzzzzzzz/pretty_json

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
