name: pretty_json
description: A small wrapper for pretty printing JSON objects
version: 1.0.0

homepage: https://github.com/Ferdzzzzzzzz/edit_json_file/pretty_json

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
