name: pretty_json
description: A small wrapper for pretty printing JSON objects in a more human readable format. Typically this package would be used for network logging and debugging objects.
version: 1.1.0-nullsafety

homepage: https://github.com/Ferdzzzzzzzz/pretty_json

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
